### DPVO Config File ###

# VO config (increase for better accuracy)
PATCHES_PER_FRAME: 96
REMOVAL_WINDOW: 22
OPTIMIZATION_WINDOW: 15
PATCH_LIFETIME: 13

# threshold for keyframe removal
KEYFRAME_THRESH: 5.0

# camera motion model
MOTION_MODEL: 'DAMPED_LINEAR'
MOTION_DAMPING: 0.5

# maybe use mixed precision for inference
MIXED_PRECISION: True

# Select between random, gradient, scorer
PATCH_SELECTOR: 'random'
# Eval mode of patch selector (random, topk, multi)
SCORER_EVAL_MODE: 'random'
SCORER_EVAL_USE_GRID: False
